// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Index documents */
interface IndexDocumentData {
  /**
   * Title field in *Index*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: index.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Intro field in *Index*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: index.intro
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  intro: prismic.RichTextField;
  /**
   * Slice Zone field in *Index*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: index.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<IndexDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *Index*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: index.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismic.KeyTextField;
  /**
   * Meta Image field in *Index*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: index.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *Index*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: index.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *Index → Slice Zone*
 *
 */
type IndexDocumentDataSlicesSlice = TwoColumnsSlice;
/**
 * Index document from Prismic
 *
 * - **API ID**: `index`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IndexDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<IndexDocumentData>, "index", Lang>;
export type AllDocumentTypes = IndexDocument;
/**
 * Primary content in TwoColumns → Primary
 *
 */
interface TwoColumnsSliceDefaultPrimary {
  /**
   * Header field in *TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.header
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  header: prismic.KeyTextField;
  /**
   * Content field in *TwoColumns → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.content
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  content: prismic.RichTextField;
  /**
   * Image field in *TwoColumns → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
}
/**
 * Default variation for TwoColumns Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TwoColumnsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TwoColumnsSliceDefaultPrimary>,
  never
>;
/**
 * Primary content in TwoColumns → Primary
 *
 */
interface TwoColumnsSliceAlternativePrimary {
  /**
   * Header field in *TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.header
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  header: prismic.KeyTextField;
  /**
   * Content field in *TwoColumns → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.content
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  content: prismic.RichTextField;
  /**
   * Image field in *TwoColumns → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
}
/**
 * Alternative variation for TwoColumns Slice
 *
 * - **API ID**: `alternative`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TwoColumnsSliceAlternative = prismic.SharedSliceVariation<
  "alternative",
  Simplify<TwoColumnsSliceAlternativePrimary>,
  never
>;
/**
 * Slice variation for *TwoColumns*
 *
 */
type TwoColumnsSliceVariation =
  | TwoColumnsSliceDefault
  | TwoColumnsSliceAlternative;
/**
 * TwoColumns Shared Slice
 *
 * - **API ID**: `two_columns`
 * - **Description**: `TwoColumns`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TwoColumnsSlice = prismic.SharedSlice<
  "two_columns",
  TwoColumnsSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      IndexDocumentData,
      IndexDocumentDataSlicesSlice,
      IndexDocument,
      AllDocumentTypes,
      TwoColumnsSliceDefaultPrimary,
      TwoColumnsSliceDefault,
      TwoColumnsSliceAlternativePrimary,
      TwoColumnsSliceAlternative,
      TwoColumnsSliceVariation,
      TwoColumnsSlice,
    };
  }
}
